<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('payments', function (Blueprint $table) {
            // One value per intended payment, generated by the browser. A
            // double-click, a refresh-resubmit or a network retry carries the
            // key the first attempt used, so the unique index rejects the
            // second insert instead of booking the client's money twice.
            //
            // Nullable on purpose: MySQL treats NULLs as distinct in a unique
            // index, so every existing caller (POS, invoices, console) keeps
            // working and simply gets no protection.
            $table->char('idempotency_key', 36)->nullable()->after('payment_number');

            $table->unique(['company_id', 'idempotency_key'], 'payments_company_idempotency_unique');
        });
    }

    public function down(): void
    {
        Schema::table('payments', function (Blueprint $table) {
            $table->dropUnique('payments_company_idempotency_unique');
            $table->dropColumn('idempotency_key');
        });
    }
};