<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('invoices', function (Blueprint $table) {
            // One value per intended sale, generated by the POS screen. A
            // network retry, a refresh-resubmit or a second tab carries the key
            // the first attempt already used, so the unique index below rejects
            // the duplicate insert instead of creating a second invoice and
            // deducting stock twice.
            //
            // Nullable on purpose: MySQL treats NULLs as distinct in a unique
            // index, so every existing caller (direct invoicing, challan
            // conversion, console) is unaffected and simply gets no protection.
            $table->char('idempotency_key', 36)->nullable()->after('invoice_number');

            $table->unique(['company_id', 'idempotency_key'], 'invoices_company_idempotency_unique');
        });
    }

    public function down(): void
    {
        Schema::table('invoices', function (Blueprint $table) {
            $table->dropUnique('invoices_company_idempotency_unique');
            $table->dropColumn('idempotency_key');
        });
    }
};